services:
  postgres:
    image: postgres:16-alpine
    container_name: taskflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow
    ports:
      - "5432:5432"
    volumes:
      - taskflow-postgres-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.7
    container_name: taskflow-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/keycloak/data
    ports:
      - "8081:8080"

volumes:
  taskflow-postgres-data:
  keycloak-data: