spring.application.name=taskflow-api

#connection to the database
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=taskflow
spring.datasource.password=taskflow
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA and Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT
jwt.secret=${JWT_SECRET:una-clave-larga-y-aleatoria-solo-para-desarrollo}
jwt.expiration=86400000

#OAuth2
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/taskflow

#Keycloak
keycloak.base-url=http://localhost:8081
keycloak.realm=taskflow

# Cliente de servicio, DISTINTO a taskflow-api, con permisos admin
keycloak.admin.client-id=taskflow-admin
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_SECRET:JcvvHtBYe8mk51e3ZlzWqOH18UPDjxq3CJ8LfLNwLDK4mDx18U6znbeHXozgXPVISIks9i3pred5L4o1MLQDfY}