spring:
  application:
    name: taskflow-api

  #CONNECTION TO POSTGRESQL
  datasource:
    url: ${DATA_SOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  #JPA AND HIBERNATE
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #FLYWAY
  flyway:
    enabled: true
    #locations: classpath:/db/migration

  #REDIS
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    type: redis
    redis:
      time-to-live: 600000

  #OAUTH2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_BASE_URL}/realms/${KEYCLOAK_REALM}

  #KAFKA
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest #latest para produccion con earliest vamos a reprocesar todo para pruebas
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#KEYCLOAK
keycloak:
  base-url: ${KEYCLOAK_BASE_URL}
  realm: ${KEYCLOAK_REALM}
  admin:
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
    client-secret: ${KEYCLOAK_ADMIN_SECRET}

#AWS FOR DYNAMODB
aws:
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT}
    region: ${AWS_DYNAMODB_REGION:us-east-1}
    access-key-id: ${AWS_DYNAMODB_ACCESS_KEY_ID}
    secret-access-key: ${AWS_DYNAMODB_SECRET_ACCESS_KEY}
    table-name: ${AWS_DYNAMODB_TABLE_NAME:TaskflowEvents}

#JWT MANUAL
#jwt.secret=${JWT_SECRET:una-clave-larga-y-aleatoria-solo-para-desarrollo}
#jwt.expiration=86400000

#RESILIENCE
resilience4j:
  circuitbreaker:
    instances:
      kafkaPublisher:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 1
      notificationRepository:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 1