apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack
          env:
            - name: SERVICES
              value: "dynamodb"
            - name: LOCALSTACK_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: localstack-secret
                  key: LOCALSTACK_AUTH_TOKEN
          ports:
            - containerPort: 4566
          volumeMounts:
            - name: init-script
              mountPath: /etc/localstack/init/ready.d/init-dynamodb.sh
              subPath: init-dynamodb.sh
          readinessProbe:
            httpGet:
              path: /_localstack/health
              port: 4566
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: init-script
          configMap:
            name: localstack-init-script
            defaultMode: 0755