apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-api-config
data:
  DATA_SOURCE_URL: "jdbc:postgresql://postgres-0.postgres:5432/taskflow"
  REDIS_HOST: "redis-0.redis"
  REDIS_PORT: "6379"
  KEYCLOAK_BASE_URL: "http://keycloak:8080"
  KEYCLOAK_REALM: "taskflow"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-0.kafka:9092"
  AWS_DYNAMODB_ENDPOINT: "http://localstack:4566"
  AWS_DYNAMODB_REGION: "us-east-1"
  AWS_DYNAMODB_TABLE_NAME: "TaskflowEvents"