apiVersion: v1
kind: Secret
metadata:
  name: taskflow-api-secret
type: Opaque
stringData:
  KEYCLOAK_ADMIN_CLIENT_ID: taskflow-admin
  KEYCLOAK_ADMIN_SECRET: 'hL8Jz8llGvk8cpzfAJ2YylvTV5FQxaWAUL6nqfw5Uks26qe21EXGVI6ZEJTCzqX4EA6D7oW7v8YDYJmcjudktK'
  AWS_DYNAMODB_ACCESS_KEY_ID: local
  AWS_DYNAMODB_SECRET_ACCESS_KEY: local